__main__ 2023-10-30 10:29:53,033 INFO Running module __main__...
__main__ 2023-10-30 10:30:16,278 INFO Successful run
__main__ 2023-10-30 10:34:28,792 INFO Running module __main__...
__main__ 2023-10-30 10:34:50,638 INFO Successful run
__main__ 2023-10-30 10:43:56,722 INFO Running module __main__...
__main__ 2023-10-30 10:44:17,865 INFO Successful run
__main__ 2023-10-30 10:44:42,081 INFO Running module __main__...
__main__ 2023-10-30 10:45:03,953 INFO Successful run
__main__ 2023-10-30 10:50:08,832 INFO Running module __main__...
__main__ 2023-10-30 10:50:30,651 INFO Successful run
__main__ 2023-10-30 10:50:43,269 INFO Running module __main__...
__main__ 2023-10-30 10:51:04,446 INFO Successful run
__main__ 2023-10-30 10:51:04,446 ERROR Some kind of error, check log file
Traceback (most recent call last):
  File "D:\workz)\parzer\python_beautifulsoup4_Parser-main\parser.py", line 256, in <module>
    zero_div = 3/0
               ~^~
ZeroDivisionError: division by zero
__main__ 2023-10-30 10:56:06,855 INFO Running module __main__...
__main__ 2023-10-30 10:56:44,681 INFO Running module __main__...
__main__ 2023-10-30 10:57:07,230 INFO Running module __main__...
__main__ 2023-10-30 10:57:29,063 INFO Successful run
__main__ 2023-10-30 10:57:29,063 ERROR Some kind of error, check log file
Traceback (most recent call last):
  File "D:\workz)\parzer\python_beautifulsoup4_Parser-main\parser.py", line 256, in <module>
    zero_div = 3/0
               ~^~
ZeroDivisionError: division by zero
